name: Test native code

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: |
        git config --global url."https://github.com/".insteadOf git://github.com/
        git submodule update --init --recursive
      
    - name: Run native tests
      working-directory: ./app/src/main/jni/tests
      run: make run_tests
